---
- name: Install WildFly Server on Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Installing JDK-11
      ansible.builtin.apt:
        name: openjdk-11-jdk
        update_cache: yes
        state: present 
    - name: Creating Group for WildFly
      ansible.builtin.group:
        name: wildfly
        state: present
    - name: Adding User to a Group
      ansible.builtin.user:
        name: wildfly
        home: /opt/wildfly
        shell: /sbin/nologin wildfly
        groups: wildfly
        state: present
    - name: Downloading WildFly
      ansible.builtin.get_url:
        url: https://download.jboss.org/wildfly/16.0.0.Final/wildfly-16.0.0.Final.tar.gz
        dest: /tmp
        group: wildfly
        owner: wildfly
    - name: Extracting WildFly
      ansible.builtin.unarchive:
        src: /tmp/wildfly-16.0.0.Final.tar.gz
        remote_src: yes
        dest: /tmp
    - name: Moving WildFly to opt  
      ansible.builtin.copy:
        src: /tmp/wildfly-16.0.0.Final/
        dest: /opt/wildfly
        remote_src: yes
    - name: Changing Ownership
      ansible.builtin.file:
        path: /opt/wildfly
        owner: wildfly
        group: wildfly
        mode: '777'
        recurse: yes
    - name: Creating a Directory
      ansible.builtin.file:
        path: /etc/wildfly
        group: wildfly
        owner: wildfly
        state: directory
    - name: Copying Configuration File 
      ansible.builtin.copy:
        src: /opt/wildfly/docs/contrib/scripts/systemd/wildfly.conf
        dest: /etc/wildfly/
        owner: wildfly
        group: wildfly
        remote_src: yes
        mode: '777'
    - name: Copying WildFly Launch Script  
      ansible.builtin.copy:
        src: /opt/wildfly/docs/contrib/scripts/systemd/launch.sh
        dest: /opt/wildfly/bin/
        owner: wildfly
        group: wildfly
        remote_src: yes
        mode: '777'
    - name: Adding Execute Permissions to Shell Files
      ansible.builtin.command: sh -c 'chmod +x /opt/wildfly/bin/*.sh'
    - name: Copying the systemd unit file to the directory 
      ansible.builtin.copy:
        src: /opt/wildfly/docs/contrib/scripts/systemd/wildfly.service
        dest: /etc/systemd/system/
        owner: wildfly
        group: wildfly
        remote_src: yes
        mode: '777'
    - name: Start & Enable the WildFly Service
      ansible.builtin.systemd:
        name: wildfly.service
        state: started
        enabled: yes
    - name: Append WildFly Console in Wildfly.conf 
      ansible.builtin.copy:
        dest: /etc/wildfly/wildfly.conf
        content: |
          # The configuration you want to run
          WILDFLY_CONFIG=standalone.xml

          # The mode you want to run
          WILDFLY_MODE=standalone

          # The address to bind to
          WILDFLY_BIND=0.0.0.0

          # The address console to bind to
          WILDFLY_CONSOLE_BIND=0.0.0.0
    - name: Append WildFly Console in launch.sh  
      ansible.builtin.copy:
        dest: /opt/wildfly/bin/launch.sh
        content: |
          #!/bin/bash

          if [ "x$WILDFLY_HOME" = "x" ]; then
              WILDFLY_HOME="/opt/wildfly"
          fi

          if [[ "$1" == "domain" ]]; then
              $WILDFLY_HOME/bin/domain.sh -c $2 -b $3 -bmanagement $4
          else
              $WILDFLY_HOME/bin/standalone.sh -c $2 -b $3 -bmanagement $4
          fi
    - name: Restart the service for changes to take effect
      ansible.builtin.systemd:
        name: wildfly.service
        state: restarted
    - name: Append WildFly Console in wildfly.service  
      ansible.builtin.copy:
        dest: /etc/systemd/system/wildfly.service
        content: |
          [Unit]
          Description=The WildFly Application Server
          After=syslog.target network.target
          Before=httpd.service

          [Service]
          Environment=LAUNCH_JBOSS_IN_BACKGROUND=1
          EnvironmentFile=-/etc/wildfly/wildfly.conf
          User=wildfly
          LimitNOFILE=102642
          PIDFile=/var/run/wildfly/wildfly.pid
          ExecStart=/opt/wildfly/bin/launch.sh $WILDFLY_MODE $WILDFLY_CONFIG $WILDFLY_BIND $WILDFLY_CONSOLE_BIND
          StandardOutput=null

          [Install]
          WantedBy=multi-user.target
    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: /var/run/wildfly/
        owner: wildfly
        group: wildfly
        mode: '777'
    - name: Reload Daemon & Restart the service 
      ansible.builtin.systemd:
        name: wildfly.service
        daemon_reload: yes 
        state: restarted

    - name: Adding WildFly User
      ansible.builtin.expect: 
        command: /opt/wildfly/bin/add-user.sh
        responses: 
          (a): "a"
          Username: "shoaib"
          Password: "Ufz@2323"
          Re-enter Password: "Ufz@2323"
          What groups do you want this user to belong to? (Please enter a comma separated list, or leave blank for none)[  ]: ': '
          Is this correct yes/no?: "yes" 
          yes/no?: "yes"